// GENERATED by scripts/pull-fonts.mjs — do not edit by hand.
import localFont from "next/font/local";

/** Anton — self-hosted (latin). CSS var --font-anton. */
export const anton = localFont({
  src: "../files/anton-400.woff2",
  display: "swap",
  variable: "--font-anton",
  fallback: ["Segoe UI", "system-ui", "sans-serif"],
  preload: true,
});
