// GENERATED by scripts/pull-fonts.mjs — do not edit by hand.
import localFont from "next/font/local";

/** Bricolage Grotesque — self-hosted (latin). CSS var --font-bricolage. */
export const bricolageGrotesque = localFont({
  src: "../files/bricolage-grotesque.woff2",
  display: "swap",
  variable: "--font-bricolage",
  fallback: ["Segoe UI", "system-ui", "sans-serif"],
  preload: true,
});
