// GENERATED by scripts/pull-fonts.mjs — do not edit by hand.
import localFont from "next/font/local";

/** Caveat — self-hosted (latin). CSS var --font-caveat. */
export const caveat = localFont({
  src: "../files/caveat.woff2",
  display: "swap",
  variable: "--font-caveat",
  fallback: ["cursive"],
  preload: true,
});
