// GENERATED by scripts/pull-fonts.mjs — do not edit by hand.
import localFont from "next/font/local";

/** Covered By Your Grace — self-hosted (latin). CSS var --font-grace. */
export const coveredByYourGrace = localFont({
  src: "../files/covered-by-your-grace-400.woff2",
  display: "swap",
  variable: "--font-grace",
  fallback: ["cursive"],
  preload: true,
});
