// GENERATED by scripts/pull-fonts.mjs — do not edit by hand.
//
// Import the per-family subpath, NEVER this file:
//   import { lora } from "@delead/fonts/lora";
// Importing a barrel here would make next/font bundle all ~17 faces
// into every app. Available families:

//   inter  ->  export { inter }
//   instrument-sans  ->  export { instrumentSans }
//   lora  ->  export { lora }
//   caveat  ->  export { caveat }
//   covered-by-your-grace  ->  export { coveredByYourGrace }
//   bricolage-grotesque  ->  export { bricolageGrotesque }
//   space-grotesk  ->  export { spaceGrotesk }
//   manrope  ->  export { manrope }
//   anton  ->  export { anton }
//   poppins  ->  export { poppins }
