// GENERATED by scripts/pull-fonts.mjs — do not edit by hand.
import localFont from "next/font/local";

/** Instrument Sans — self-hosted (latin). CSS var --font-instrument. */
export const instrumentSans = localFont({
  src: [
    { path: "../files/instrument-sans.woff2", weight: "400 700", style: "normal" },
    { path: "../files/instrument-sans-italic.woff2", weight: "400 700", style: "italic" },
  ],
  display: "swap",
  variable: "--font-instrument",
  fallback: ["system-ui", "sans-serif"],
  preload: true,
});
