// GENERATED by scripts/pull-fonts.mjs — do not edit by hand.
import localFont from "next/font/local";

/** Lora — self-hosted (latin). CSS var --font-lora. */
export const lora = localFont({
  src: [
    { path: "../files/lora.woff2", weight: "400 700", style: "normal" },
    { path: "../files/lora-italic.woff2", weight: "400 700", style: "italic" },
  ],
  display: "swap",
  variable: "--font-lora",
  fallback: ["Georgia", "serif"],
  preload: true,
});
