// GENERATED by scripts/pull-fonts.mjs — do not edit by hand.
import localFont from "next/font/local";

/** Manrope — self-hosted (latin). CSS var --font-manrope. */
export const manrope = localFont({
  src: "../files/manrope.woff2",
  display: "swap",
  variable: "--font-manrope",
  fallback: ["system-ui", "sans-serif"],
  preload: true,
});
