// GENERATED by scripts/pull-fonts.mjs — do not edit by hand.
import localFont from "next/font/local";

/** Poppins — self-hosted (latin). CSS var --font-poppins. */
export const poppins = localFont({
  src: [
    { path: "../files/poppins-300.woff2", weight: "300", style: "normal" },
    { path: "../files/poppins-400.woff2", weight: "400", style: "normal" },
    { path: "../files/poppins-500.woff2", weight: "500", style: "normal" },
    { path: "../files/poppins-600.woff2", weight: "600", style: "normal" },
    { path: "../files/poppins-700.woff2", weight: "700", style: "normal" },
    { path: "../files/poppins-800.woff2", weight: "800", style: "normal" },
  ],
  display: "swap",
  variable: "--font-poppins",
  fallback: ["-apple-system", "BlinkMacSystemFont", "Segoe UI", "sans-serif"],
  preload: true,
});
