// GENERATED by scripts/pull-fonts.mjs — do not edit by hand.
import localFont from "next/font/local";

/** Space Grotesk — self-hosted (latin). CSS var --font-space-grotesk. */
export const spaceGrotesk = localFont({
  src: "../files/space-grotesk.woff2",
  display: "swap",
  variable: "--font-space-grotesk",
  fallback: ["system-ui", "sans-serif"],
  preload: true,
});
